#!/bin/bash

# run with initial preceding dot, as:
#   . ./scripts/expo 
# or 
#   source ./scripts/expo
# details here - http://stackoverflow.com/a/28489593

export PORT=8000
export PGHOST=$CP_PG_SVR_PORT_5432_TCP_ADDR
export PGUSER=postgres, export PGUSER=carpool_web
export PGPASSWORD=$CP_PG_SVR_ENV_POSTGRES_PASSWORD
export PGDATABASE=carpool.dev, export PGDATABASE=carpool

echo "exports added"
